[tool.poetry]
name = "yahoo stocks"
version = "0.1.0"
description = "Simple script to fetch & manipulate stocks data from the Yahoo Finance API for insights"
authors = ["f1she3 <f1she3@protonmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytickersymbols = "^1.17.1"
yfinance = "^1.0.0"
pandas = "^2.3.3"
pyyaml = "^6.0.3"
rich = "^14.2.0"

[tool.poetry.group.dev.dependencies]
poetry = "^2.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
